FROM eclipse-mosquitto:latest
#COPY mosquitto.conf /mosquitto/config/
#COPY mosquitto.conf /etc/mosquitto/conf.d
#WORKDIR /mosquitto/config/
#RUN mkdir -p /mosquitto/config/
#WORKDIR /mosquitto/config/
COPY ./mosquitto.conf /mosquitto/config/
